### ISSUE TITLE
Create DirectStrategy

### ISSUE THREAD

**Issue by pragalli** [BootNodeDev/allo-protocol-contracts#1]
Create a new contract DirectStrategy which would be used as the strategy for a RoundImplementation:
- This contract should contain the necessary logic for paying grants to accepted application
- Payments should flow from an external account to the applicant account

**Comment by lmcorbalan** [comment]
Current version on https://github.com/BootNodeDev/allo-protocol-contracts/pull/3 is a very basic one.
Needed to move quickly to provide the FE team something to work with.
Ideally interfaces wont change, just the logic will be improved.
